/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manish.projecteuler;

import java.util.logging.Logger;

/**
 *
 * @author manish
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
public class P02EvenFibonacciNumbers {
    static final Logger log = Logger.getLogger(P01MultipleOf3And5.class.getName());
    
    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        SumEvenFibonacci(4000000);
        
    }
     
    /**
     * This Function calculates the sum of Even Fibonacci Series
     * 
     * @param range
     * @return
     */
    public static int SumEvenFibonacci (int range) {
        //starting from 3 as we are initalizing sum = 2 which is first even fibonnaci series number
        int firstTerm= 3, secondTerm=5,  thirdTerm =0, sum=2;
        while (thirdTerm <= range) { 
           thirdTerm = firstTerm + secondTerm;
           if ( thirdTerm % 2 == 0) {
               sum = sum + thirdTerm;
           }
           firstTerm = secondTerm;
           secondTerm = thirdTerm;            
        }
        log.info("Sum of even febonacci series is "+ sum);
        System.out.println("Sum of even febonacci series less than "+ range +" is: "+ sum);
        return sum;
    }
    
    
}
